### ISSUE TITLE
App crash on launch on android 7.0 and 8.1

### ISSUE THREAD

**Issue by darewealth** [gauravjot/android-noad-music-player#6] opened 2019-06-05 20:16 UTC
### Describe the bug.
The app crash on launch when I open it on android 7.0 and 8.1, but it works on 6.1

### Steps to reproduce.
* Launch the app

* And note the bug

### Expected Behaviour
I expect to use it on every android version. 

### Screen recording
https://youtu.be/INsVkwnXW5A

### Devices and Versions.

Device: [Gionee X1]

Version [7.0]

App version [0.9.4]

### Log
```06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: FATAL EXCEPTION: main
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: Process: com.droidheat.musicplayer, PID: 20770
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class ImageView
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class ImageView
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f08007f
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08007f
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:253)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:760)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:886)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:188)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.ImageView.<init>(ImageView.java:171)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at com.droidheat.musicplayer.CustomAdapter.getView(CustomAdapter.java:74)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at com.commonsware.cwac.merge.MergeAdapter.getView(MergeAdapter.java:271)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2365)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2052)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.ListView.fillSpecific(ListView.java:1482)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1803)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:2164)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.878 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.View.layout(View.java:19806)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6150)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2597)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2302)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6982)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:913)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:725)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:660)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:899)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-05 20:04:14.879 10110 20770 20770 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)```

**Comment by gauravjot** [comment] 2019-06-05 20:31
I can confirm it working on Android 8.1. Can you uninstall app and install it again and let me know if issue still exist? Also try to clear app data in settings > apps > Noad Player > storage.

**Comment by darewealth** [comment] 2019-06-05 20:43
I did as you have directed but after I granted all the permission, the app crashed. Adding a short clip of the behavior. https://youtu.be/5IJZ-VmJwyk

**Comment by gauravjot** [comment] 2019-06-06 04:05
I will look into it why it might be occurring. I have my phone on Android 8.1 working just fine. Thank you for filing an issue!

**Comment by gauravjot** [comment] 2019-06-17 21:15
I just released a beta update for the app on Play Store. Please let me know if the issue still persists for you.

**Comment by darewealth** [comment] 2019-06-26 05:55
I can't find the improved version on playstore

**Comment by gauravjot** [comment] 2019-06-27 22:49
It's beta version 0.9.49. Check it under settings menu of app. Please let me know if app still crashes for you. Also if it is possible to share a new crashllog, that will be great.

**Comment by gauravjot** [comment] 2019-07-11 05:42
I am closing the issue due to the lack of data points on how this crash is caused. The crash might have been resolved in newer releases. If it still occurs for you, please let me know.

**Closed as completed by gauravjot** 2019-07-11 05:42 UTC
Labels: question, crash
